# Generated by Django 4.2.2 on 2023-06-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=50, verbose_name='Order Name')),
                ('order_amount', models.IntegerField(verbose_name='Order Amount')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.user', verbose_name='User FK')),
            ],
        ),
    ]
