# Generated by Django 4.2.2 on 2023-07-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role_Faker',
            new_name='Role_Faker1',
        ),
        migrations.RenameModel(
            old_name='Task_Faker',
            new_name='Task_Faker1',
        ),
        migrations.RenameModel(
            old_name='User_Faker',
            new_name='User_Faker1',
        ),
    ]
