# Generated by Django 4.2.2 on 2023-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=264, unique=True),
            preserve_default=False,
        ),
    ]
