# Generated by Django 4.2.2 on 2023-07-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
