# Generated by Django 4.2.2 on 2023-07-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0003_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='wdwd', max_length=264),
            preserve_default=False,
        ),
    ]
