# Generated by Django 4.2.2 on 2023-07-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0003_user_is_active_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
