# Generated by Django 4.2.2 on 2023-07-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_faker',
            name='role',
        ),
        migrations.RemoveField(
            model_name='task_faker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_faker',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role_Faker',
        ),
        migrations.DeleteModel(
            name='Task_Faker',
        ),
        migrations.DeleteModel(
            name='User_Faker',
        ),
    ]
