# Generated by Django 4.2.2 on 2023-07-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0007_user_otp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
    ]
