# Generated by Django 4.2.2 on 2023-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0010_remove_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
