# Generated by Django 4.2.2 on 2023-07-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0012_remove_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret_key',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
