# Generated by Django 4.2.2 on 2023-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0013_user_totp_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
